/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  KlayBatchTrasnfer,
  KlayBatchTrasnferInterface,
} from "../KlayBatchTrasnfer";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_toList",
        type: "address[]",
      },
      {
        name: "_valueList",
        type: "uint256[]",
      },
    ],
    name: "klayBatchTransfer",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610384806100206000396000f3fe60806040526004361061001e5760003560e01c8063d01c9bf014610023575b600080fd5b6100ef6004803603604081101561003957600080fd5b810190808035906020019064010000000081111561005657600080fd5b82018360208201111561006857600080fd5b8035906020019184602083028401116401000000008311171561008a57600080fd5b9091929391929390803590602001906401000000008111156100ab57600080fd5b8201836020820111156100bd57600080fd5b803590602001918460208302840111640100000000831117156100df57600080fd5b90919293919293905050506100f1565b005b81819050848490501461016c576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260198152602001807f4172726179206c656e67746820697320646966666572656e740000000000000081525060200191505060405180910390fd5b600080905060008090505b838390508210156101b5576101a784848481811061019157fe5b90506020020135826102d090919063ffffffff16565b508180600101925050610177565b80341461022a576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260198152602001807f496e636f7272656374207472616e7366657220616d6f756e740000000000000081525060200191505060405180910390fd5b600091505b858590508210156102c85785858381811061024657fe5b9050602002013573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc85858581811061028857fe5b905060200201359081150290604051600060405180830381858888f193505050501580156102ba573d6000803e3d6000fd5b50818060010192505061022f565b505050505050565b60008082840190508381101561034e576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252601b8152602001807f536166654d6174683a206164646974696f6e206f766572666c6f77000000000081525060200191505060405180910390fd5b809150509291505056fea165627a7a72305820c7a038fcffa28fee498328e27dd9af2eba103a5bbe73d0d433801f51bad82d630029";

type KlayBatchTrasnferConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: KlayBatchTrasnferConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class KlayBatchTrasnfer__factory extends ContractFactory {
  constructor(...args: KlayBatchTrasnferConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<KlayBatchTrasnfer> {
    return super.deploy(overrides || {}) as Promise<KlayBatchTrasnfer>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): KlayBatchTrasnfer {
    return super.attach(address) as KlayBatchTrasnfer;
  }
  connect(signer: Signer): KlayBatchTrasnfer__factory {
    return super.connect(signer) as KlayBatchTrasnfer__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): KlayBatchTrasnferInterface {
    return new utils.Interface(_abi) as KlayBatchTrasnferInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KlayBatchTrasnfer {
    return new Contract(address, _abi, signerOrProvider) as KlayBatchTrasnfer;
  }
}
